when:
  - event: push
    branch: main

steps:
  build:
    image: node:20
    commands:
      - corepack enable
      - corepack prepare pnpm@latest --activate
      - pnpm install --frozen-lockfile
      - pnpm turbo build

  deploy:
    image: node:20
    commands:
      - corepack enable
      - corepack prepare pnpm@latest --activate
      - pnpm turbo deploy
    environment:
      CLOUDFLARE_API_TOKEN:
        from_secret: CLOUDFLARE_API_TOKEN
